const root=document.querySelector('#app');
let home, activePage='home', theme='dark', expanded=new Set(), queryIndex=-1;
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data};
const esc=value=>String(value??'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number=value=>value==null?'—':typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:2}):esc(value);
const signed=value=>value==null?'—':`${value>=0?'+':''}${Number(value).toFixed(1)}%`;

function setTheme(next){theme=next;document.documentElement.dataset.theme=theme;const button=document.querySelector('#theme-toggle');if(button){button.innerHTML=theme==='dark'?'☀':'☾';button.setAttribute('aria-label',theme==='dark'?'Use light theme':'Use dark theme')}}
function shell(content,options={}){const demo=options.demo??home?.demo;root.innerHTML=`<div class="app-shell"><header class="topbar"><button class="wordmark" onclick="load()" aria-label="Smart Market Watchlist home"><span></span>Smart Market Watchlist</button><nav class="desktop-nav" aria-label="Primary"><button class="${activePage==='home'?'active':''}" onclick="load()">Home</button><button class="${activePage==='watch'?'active':''}" onclick="watch()">Watchlist</button><button class="${activePage==='settings'?'active':''}" onclick="settings()">Settings</button></nav><div class="top-actions"><div class="global-search"><label class="sr-only" for="global-query">Search securities</label><input id="global-query" autocomplete="off" placeholder="Search" oninput="search(this.value)" onkeydown="searchKeys(event)" onblur="setTimeout(closeSearch,160)"><div id="search-results" class="search-results" role="listbox"></div></div>${demo?'<span class="demo-badge" title="Simulated data for development">Demo</span>':''}<button id="theme-toggle" class="icon-button" onclick="setTheme(theme==='dark'?'light':'dark')" aria-label="Use light theme">☀</button><button class="quiet logout" onclick="logout()">Log out</button></div></header>${content}<nav class="mobile-nav" aria-label="Primary"><button class="${activePage==='home'?'active':''}" onclick="load()">Home</button><button class="${activePage==='watch'?'active':''}" onclick="watch()">Watchlist</button><button class="${activePage==='settings'?'active':''}" onclick="settings()">Settings</button></nav></div>`;setTheme(theme)}
function skeleton(){shell(`<main><div class="skeleton heading"></div><div class="skeleton row"></div><div class="skeleton row"></div><div class="skeleton row"></div></main>`)}

function tier(tier){return tier==='Normal'?'':`<span class="tier ${tier.toLowerCase()}">${esc(tier)}</span>`}
function catchupRow(stock,full=false){const isOpen=expanded.has(stock.symbol), moveClass=stock.move>=0?'positive':'negative';return `<article class="update-row ${isOpen?'open':''} ${stock.tier==='Significant'?'significant-row':''}"><button class="row-main" onclick="detail('${stock.symbol}')" aria-label="Open ${esc(stock.name)}"><span class="identity"><b>${esc(stock.symbol)}</b><span>${esc(stock.name)}</span></span>${tier(stock.tier)}<span class="quote"><b>${number(stock.price)}</b><strong class="${moveClass}">${signed(stock.move)}</strong></span></button><button class="expand" onclick="toggleCard('${stock.symbol}')" aria-expanded="${isOpen}">${isOpen?'Show less ⌃':'Show more ⌄'}</button><div class="row-detail"><div><ul class="evidence">${(stock.evidence||[]).map(item=>`<li>${esc(item)}</li>`).join('')}</ul><div class="detail-meta"><span>Confidence <b>${esc(stock.confidence)}</b></span><span>${esc(stock.freshness)}</span><span>Peers <b>${signed(stock.relative)}</b></span><span>Volume <b>${number(stock.volume)}×</b></span></div></div><button class="primary compact" onclick="review('${stock.symbol}')">Review</button></div></article>`}
function pulse(p){return `<div class="pulse-row">${['significant','notable','normal'].map(key=>`<button onclick="filterTier('${key}')"><b>${p?.[key]??0}</b><span>${key}</span></button>`).join('')}</div>`}
function context(items){return items?.length?`<div class="context-strip">${items.map(item=>`<span><b>${esc(item.sector)}</b><em class="${item.move>=0?'positive':'negative'}">${signed(item.move)}</em><small>${item.tracked} tracked</small></span>`).join('')}</div>`:'<p class="muted">Sector context will appear after watched securities have data.</p>'}
function table(rows){return `<div class="watchlist-table"><div class="table-head"><span>Security</span><span>Price</span><span>Move</span><span>Status</span></div>${rows.map(stock=>`<button class="table-row" onclick="detail('${stock.symbol}')"><span><b>${esc(stock.name)}</b><small>${esc(stock.symbol)} · ${esc(stock.sector)}</small></span><strong class="numbers">${number(stock.price)}</strong><strong class="numbers ${stock.move>=0?'positive':'negative'}">${signed(stock.move)}</strong><span>${tier(stock.tier)||'<small>Normal</small>'}</span></button>`).join('')}</div>`}

async function load(){activePage='home';skeleton();try{home=await api('/api/home');const watchlist=home.watchlist||[],catchUp=home.catchUp||[];shell(`<main><section class="home-heading"><div><p class="eyebrow">Your watchlist</p><h1>${watchlist.length?'A quieter way to keep up.':'Start with what matters.'}</h1><p class="muted">${esc(home.updated)}</p></div><button class="quiet refresh" onclick="refreshData()">↻ Refresh</button></section><section class="catchup-section"><div class="section-heading"><div><p class="eyebrow">Catch-up</p><h2>Worth your attention</h2></div>${catchUp.length>1?'<button class="quiet" onclick="reviewAll()">Review all</button>':''}</div>${catchUp.length?`<div class="updates">${catchUp.map(item=>catchupRow(item)).join('')}</div>`:`<div class="calm-empty"><b>Nothing needs your attention right now.</b><span>${watchlist.length?'Your watchlist is quiet.':'Search for a security to begin.'}</span></div>`}${home.catchUpOverflow?`<button class="more-link" onclick="showOverflow()">+${home.catchUpOverflow} more updates</button>`:''}</section><div class="home-context"><section><p class="eyebrow">Pulse</p>${pulse(home.pulse)}</section><section><p class="eyebrow">Market context</p>${context(home.marketContext)}</section></div><section class="full-watchlist"><div class="section-heading"><div><p class="eyebrow">Full watchlist</p><h2>Everything you follow</h2></div><button class="quiet" onclick="watch()">Manage</button></div>${watchlist.length?table(watchlist):'<div class="calm-empty">Use search to add your first security.</div>'}</section></main>`,home)}catch(error){auth(error.message)}}

function toggleCard(symbol){expanded.has(symbol)?expanded.delete(symbol):expanded.add(symbol);load()}
async function review(symbol){await api('/api/acknowledgments',{method:'POST',body:JSON.stringify({symbol})});expanded.delete(symbol);load()}
async function reviewAll(){for(const item of home.catchUp||[])await api('/api/acknowledgments',{method:'POST',body:JSON.stringify({symbol:item.symbol})});load()}
async function refreshData(){try{await api('/api/refresh',{method:'POST'});load()}catch(error){alert('Market refresh failed. Existing data remains available.')}}
function showOverflow(){activePage='home';shell(`<main><button class="back" onclick="load()">← Home</button><section class="catchup-section"><p class="eyebrow">More updates</p><h1>Other notable changes</h1><div class="updates">${home.watchlist.filter(item=>item.tier!=='Normal'&&!item.reviewed).map(item=>catchupRow(item)).join('')}</div></section></main>`,home)}
function filterTier(tierName){shell(`<main><button class="back" onclick="load()">← Home</button><section class="catchup-section"><p class="eyebrow">Watchlist pulse</p><h1>${esc(tierName)}</h1><div class="updates">${home.watchlist.filter(item=>item.tier.toLowerCase()===tierName).map(item=>catchupRow(item)).join('')}</div></section></main>`,home)}

async function detail(symbol){activePage='';skeleton();try{const data=await api('/api/stocks/'+symbol),insight=data.insight,comparison=data.comparison,contextData=data.context||{};const move=comparison?.percentageDifference;const evidence=insight?JSON.parse(insight.evidence_json):[];shell(`<main><button class="back" onclick="load()">← Watchlist</button><section class="stock-header"><div><p class="eyebrow">${esc(data.stock.exchange)} · ${esc(data.stock.sector)}</p><h1>${esc(data.stock.symbol)}</h1><p class="muted">${esc(data.stock.name)}</p></div><div class="headline"><b>${number(comparison?.currentPrice??insight?.current_price)}</b><span class="${move>=0?'positive':'negative'}">${comparison?`${comparison.absoluteDifference>=0?'+':''}${number(comparison.absoluteDifference)} · ${signed(move)}`:'—'}</span><small>${data.reviewed?'Reviewed':'Needs review'}</small></div></section>${insight?`<section class="detail-layout"><article class="reading-block"><p class="eyebrow">Why it surfaced</p><h2>${tier(insight.tier)} Evidence</h2><ul class="evidence">${evidence.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><div class="detail-meta"><span>Confidence <b>${esc(insight.confidence)}</b></span><span>${esc(insight.freshness)}</span></div><button class="primary" onclick="review('${symbol}')">${data.reviewed?'Reviewed':'Review update'}</button></article><article class="reading-block chart-block"><p class="eyebrow">Price history</p>${chart(data.history||[],data.timeline||[])}</article></section>`:'<div class="calm-empty">No snapshot history is available yet.</div>'}<section class="detail-layout"><article class="reading-block"><p class="eyebrow">Context, not cause</p><h2>Peers & benchmark</h2><p class="muted">${esc(contextData.label||'Comparisons are context only.')}</p><div class="context-metrics"><span>Benchmark <b>${contextData.benchmarkSymbol||'—'}</b><em>${signed(contextData.benchmarkMove)}</em></span><span>Peers <b>${signed(contextData.peerMove)}</b></span></div>${(contextData.peers||[]).map(peer=>`<p class="peer"><b>${esc(peer.symbol)}</b> ${esc(peer.name)} <span>${peer.move==null?esc(peer.freshness):signed(peer.move)}</span></p>`).join('')}</article><article class="reading-block"><p class="eyebrow">Timeline</p><div class="filters">${['All','Company','Sector','Domestic','Global'].map(layer=>`<button onclick="timeline('${symbol}','${layer}')">${layer}</button>`).join('')}</div><div id="timeline">${(data.timeline||[]).slice(0,4).map(eventCard).join('')||'<p class="muted">No provider events available.</p>'}</div></article></section></main>`,home)}catch(error){shell(`<main><div class="calm-empty"><b>Stock detail is unavailable.</b><span>${esc(error.message)}</span><button class="quiet" onclick="load()">Back to watchlist</button></div></main>`,home)}}
function chart(history,events){if(history.length<2)return '<p class="muted">No historical data yet.</p>';const values=history.map(item=>item.price),min=Math.min(...values),max=Math.max(...values),range=max-min||1,points=values.map((value,index)=>`${index/(values.length-1)*100},${94-(value-min)/range*84}`).join(' ');const markers=events.map(event=>{const index=history.findIndex(item=>item.timestamp.slice(0,10)===event.timestamp.slice(0,10));return index<0?'':`<circle cx="${index/(history.length-1)*100}" cy="${94-(history[index].price-min)/range*84}" r="1.8"/>`}).join('');return `<svg class="history-chart" viewBox="0 0 100 100" role="img" aria-label="Historical price chart"><line x1="0" y1="94" x2="100" y2="94"/><polyline points="${points}"/>${markers}</svg><small>${esc(history[0].timestamp.slice(0,10))} — ${esc(history.at(-1).timestamp.slice(0,10))}</small>`}
const eventCard=event=>`<article class="timeline-event"><small>${esc(event.timestamp.slice(0,10))} · ${esc(event.layer)}</small><b>${esc(event.title)}</b>${event.detail?`<span>${esc(event.detail)}</span>`:''}</article>`;
async function timeline(symbol,layer){const target=document.querySelector('#timeline');try{const data=await api(`/api/stocks/${symbol}/timeline?layer=${encodeURIComponent(layer)}`);target.innerHTML=(data.events||[]).map(eventCard).join('')||'<p class="muted">No events in this layer.</p>'}catch{target.innerHTML='<p class="muted">Timeline unavailable.</p>'}}

async function watch(){activePage='watch';skeleton();try{const management=await api('/api/watchlist/manage');shell(`<main><section class="page-title"><p class="eyebrow">Watchlist</p><h1>Follow only what you want to notice.</h1><p class="muted">${management.entries.length} of 100 securities</p></section><section class="add-security"><label for="manage-search">Add a security</label><input id="manage-search" placeholder="Search symbol or company" oninput="manageSearch(this.value)"><div id="manage-results" class="search-results inline"></div></section><section class="manage-list">${management.entries.map(entry=>`<article><div><b>${esc(entry.name)}</b><span>${esc(entry.symbol)} · ${esc(entry.watch_type)}${entry.expires_at?` · expires ${esc(entry.expires_at.slice(0,10))}`:''}</span></div><div><button class="quiet" onclick="manage('${entry.symbol}','mute',${entry.mute?0:1})">${entry.mute?'Unmute':'Mute'}</button><button class="quiet" onclick="${entry.watch_type==='permanent'?`temporary('${entry.symbol}')`:`manage('${entry.symbol}','watchType','permanent')`}">${entry.watch_type==='permanent'?'Watch 7 days':'Make permanent'}</button><button class="danger-link" onclick="removeStock('${entry.symbol}')">Remove</button></div></article>`).join('')||'<div class="calm-empty">Search above to add your first security.</div>'}</section></main>`,home)}catch(error){shell(`<main><div class="calm-empty">Watchlist unavailable. <button class="quiet" onclick="watch()">Retry</button></div></main>`,home)}}
async function manageSearch(value){const target=document.querySelector('#manage-results');if(!value.trim()){target.innerHTML='';return}try{const data=await api('/api/search?q='+encodeURIComponent(value));target.innerHTML=data.results.map(result=>`<button onclick="add('${result.symbol}')"><b>${esc(result.symbol)}</b><span>${esc(result.name)} · ${esc(result.exchange)}</span><em>Add</em></button>`).join('')||'<span class="muted">No matching securities.</span>'}catch{target.innerHTML='<span class="muted">Search unavailable.</span>'}}
async function add(symbol){await api('/api/watchlist',{method:'POST',body:JSON.stringify({symbol})});watch()}
async function removeStock(symbol){if(confirm(`Remove ${symbol} from your watchlist?`)){await api('/api/watchlist/'+symbol,{method:'DELETE'});watch()}}
async function manage(symbol,key,value){await api('/api/watchlist/manage',{method:'POST',body:JSON.stringify({symbol,[key]:value})});watch()}
async function temporary(symbol){await api('/api/watchlist/manage',{method:'POST',body:JSON.stringify({symbol,watchType:'temporary',expiresAt:new Date(Date.now()+7*86400000).toISOString()})});watch()}

async function settings(){activePage='settings';skeleton();try{const preferences=await api('/api/settings'),labels={price:'Price moves',volume:'Volume anomalies',news:'News',earnings:'Earnings',corporate_actions:'Corporate actions'},categories=['announcement','earnings','corporate action','market'];shell(`<main class="settings-page"><section class="page-title"><p class="eyebrow">Settings</p><h1>What you want to notice.</h1><p class="muted">These choices affect visibility, never objective significance.</p></section><section class="preferences">${Object.entries(labels).map(([key,label])=>`<div><span><b>${label}</b><small>Show this evidence when it is available.</small></span><button class="switch ${preferences[key]?'on':''}" onclick="setPref('${key}',${preferences[key]?0:1})" aria-label="Toggle ${label}"><i></i></button></div>`).join('')}</section><section class="muted-categories"><p class="eyebrow">Muted categories</p><div>${categories.map(category=>`<button class="chip ${preferences.mutedCategories.includes(category)?'muted-chip':''}" onclick="setCategoryMute('${category}',${preferences.mutedCategories.includes(category)?0:1})">${esc(category)} ${preferences.mutedCategories.includes(category)?'×':'+'}</button>`).join('')}</div></section></main>`,home)}catch(error){shell(`<main><div class="calm-empty">Settings unavailable. <button class="quiet" onclick="settings()">Retry</button></div></main>`,home)}}
async function setPref(key,value){await api('/api/settings',{method:'POST',body:JSON.stringify({[key]:value})});settings()}
async function setCategoryMute(category,muted){await api('/api/settings/muted-categories',{method:'POST',body:JSON.stringify({category,muted})});settings()}

async function search(value){const target=document.querySelector('#search-results');queryIndex=-1;if(!value.trim()){target.innerHTML='';return}try{const data=await api('/api/search?q='+encodeURIComponent(value));target.innerHTML=data.results.map((item,index)=>`<button role="option" data-symbol="${esc(item.symbol)}" onclick="add('${item.symbol}')"><b>${esc(item.symbol)}</b><span>${esc(item.name)}</span><small>${esc(item.exchange)}</small></button>`).join('')||'<span class="muted">No matches</span>'}catch{target.innerHTML='<span class="muted">Search unavailable</span>'}}
function searchKeys(event){const choices=[...document.querySelectorAll('#search-results button')];if(event.key==='Escape'){event.currentTarget.value='';closeSearch()}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();queryIndex=(queryIndex+(event.key==='ArrowDown'?1:-1)+choices.length)%choices.length;choices.forEach((button,index)=>button.classList.toggle('selected',index===queryIndex))}if(event.key==='Enter'&&queryIndex>=0){event.preventDefault();choices[queryIndex]?.click()}}
function closeSearch(){const target=document.querySelector('#search-results');if(target)target.innerHTML=''}
async function logout(){await fetch('/api/auth/logout',{method:'POST'});auth()}
function auth(message=''){root.innerHTML=`<div class="auth-shell"><section><button class="wordmark" onclick="auth()"><span></span>Smart Market Watchlist</button><p class="eyebrow">Evidence-first watchlist</p><h1>Keep up without the noise.</h1><form id="auth-form"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="primary">Continue</button><small>${esc(message)}</small></form></section></div>`;document.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();const body=JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)));try{await api('/api/auth/login',{method:'POST',body})}catch{await api('/api/auth/signup',{method:'POST',body})}load()}}
Object.assign(window,{load,watch,settings,setTheme,refreshData,toggleCard,detail,review,reviewAll,showOverflow,filterTier,timeline,manageSearch,add,removeStock,manage,temporary,setPref,setCategoryMute,search,searchKeys,closeSearch,logout,auth});
setTheme(theme);load();
